// Code generated by protoc-gen-go. DO NOT EDIT.
// source: share/proto/backup.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Chat struct {
	MessageId            string   `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	RoomId               string   `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	ClientUid            string   `protobuf:"bytes,6,opt,name=clientUid,proto3" json:"clientUid,omitempty"`
	Data                 string   `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chat) Reset()         { *m = Chat{} }
func (m *Chat) String() string { return proto.CompactTextString(m) }
func (*Chat) ProtoMessage()    {}
func (*Chat) Descriptor() ([]byte, []int) {
	return fileDescriptor_89121a16b2518d2d, []int{0}
}

func (m *Chat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chat.Unmarshal(m, b)
}
func (m *Chat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chat.Marshal(b, m, deterministic)
}
func (m *Chat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chat.Merge(m, src)
}
func (m *Chat) XXX_Size() int {
	return xxx_messageInfo_Chat.Size(m)
}
func (m *Chat) XXX_DiscardUnknown() {
	xxx_messageInfo_Chat.DiscardUnknown(m)
}

var xxx_messageInfo_Chat proto.InternalMessageInfo

func (m *Chat) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *Chat) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *Chat) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Chat) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Chat) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Chat) GetClientUid() string {
	if m != nil {
		return m.ClientUid
	}
	return ""
}

func (m *Chat) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_89121a16b2518d2d, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Status struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_89121a16b2518d2d, []int{2}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*Chat)(nil), "proto.Chat")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*Status)(nil), "proto.Status")
}

func init() {
	proto.RegisterFile("share/proto/backup.proto", fileDescriptor_89121a16b2518d2d)
}

var fileDescriptor_89121a16b2518d2d = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x95, 0x36, 0x7f, 0xe8, 0x15, 0x18, 0x6e, 0x40, 0x56, 0xc5, 0x80, 0x32, 0xa0, 0x4e,
	0xad, 0x04, 0xdf, 0x00, 0xc4, 0xd0, 0x01, 0x21, 0x05, 0xb1, 0xb0, 0x5d, 0x1b, 0x8b, 0x46, 0x25,
	0xb1, 0x15, 0x5f, 0x86, 0x7c, 0x33, 0x3e, 0x1e, 0xf6, 0x39, 0xa2, 0x62, 0xca, 0xbd, 0xdf, 0xd3,
	0xbb, 0xcb, 0x33, 0x28, 0x77, 0xa4, 0x5e, 0x6f, 0x6d, 0x6f, 0xd8, 0x6c, 0xf7, 0x74, 0x38, 0x0d,
	0x76, 0x23, 0x02, 0x33, 0xf9, 0x94, 0x3f, 0x09, 0xa4, 0xcf, 0x47, 0x62, 0xbc, 0x85, 0x45, 0xab,
	0x9d, 0xa3, 0x2f, 0xbd, 0xab, 0x55, 0x72, 0x97, 0xac, 0x17, 0xd5, 0x19, 0xe0, 0x0d, 0xe4, 0xbd,
	0x31, 0xad, 0xb7, 0x66, 0x62, 0x4d, 0x2a, 0xf0, 0xc1, 0xe9, 0xde, 0xf3, 0x79, 0xe4, 0x51, 0x85,
	0x6d, 0xdc, 0xf8, 0x38, 0x53, 0x6b, 0x55, 0xea, 0xad, 0x79, 0x75, 0x06, 0x88, 0x90, 0xf2, 0x68,
	0xb5, 0xca, 0x24, 0x23, 0x73, 0x48, 0x1c, 0xbe, 0x1b, 0xdd, 0xf1, 0x47, 0x53, 0xab, 0x3c, 0xde,
	0xff, 0x03, 0x21, 0x51, 0x13, 0x93, 0x2a, 0x62, 0x22, 0xcc, 0x65, 0x01, 0xd9, 0x4b, 0x6b, 0x79,
	0x2c, 0x15, 0xe4, 0xef, 0x4c, 0x3c, 0x38, 0xbc, 0x86, 0x99, 0x39, 0xc9, 0xdf, 0x5f, 0x54, 0x7e,
	0x7a, 0xf8, 0x84, 0xfc, 0x49, 0x4a, 0xe3, 0x1a, 0x96, 0x6f, 0xdd, 0xeb, 0xd4, 0xa7, 0xc3, 0x65,
	0x7c, 0x85, 0x4d, 0xa8, 0xbe, 0xba, 0x9c, 0x84, 0x6c, 0xc3, 0x7b, 0x28, 0x76, 0xae, 0xd2, 0x54,
	0x8f, 0xf8, 0xcf, 0x58, 0x5d, 0x4d, 0x2a, 0xde, 0xda, 0xe7, 0xa2, 0x1e, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x2b, 0xee, 0xf6, 0x2d, 0x63, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BackupClient is the client API for Backup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BackupClient interface {
	OnMessageIn(ctx context.Context, in *Chat, opts ...grpc.CallOption) (*Empty, error)
	IsReady(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
}

type backupClient struct {
	cc grpc.ClientConnInterface
}

func NewBackupClient(cc grpc.ClientConnInterface) BackupClient {
	return &backupClient{cc}
}

func (c *backupClient) OnMessageIn(ctx context.Context, in *Chat, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Backup/OnMessageIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupClient) IsReady(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/proto.Backup/IsReady", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackupServer is the server API for Backup service.
type BackupServer interface {
	OnMessageIn(context.Context, *Chat) (*Empty, error)
	IsReady(context.Context, *Empty) (*Status, error)
}

// UnimplementedBackupServer can be embedded to have forward compatible implementations.
type UnimplementedBackupServer struct {
}

func (*UnimplementedBackupServer) OnMessageIn(ctx context.Context, req *Chat) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessageIn not implemented")
}
func (*UnimplementedBackupServer) IsReady(ctx context.Context, req *Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReady not implemented")
}

func RegisterBackupServer(s *grpc.Server, srv BackupServer) {
	s.RegisterService(&_Backup_serviceDesc, srv)
}

func _Backup_OnMessageIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Chat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServer).OnMessageIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Backup/OnMessageIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServer).OnMessageIn(ctx, req.(*Chat))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backup_IsReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServer).IsReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Backup/IsReady",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServer).IsReady(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Backup_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Backup",
	HandlerType: (*BackupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessageIn",
			Handler:    _Backup_OnMessageIn_Handler,
		},
		{
			MethodName: "IsReady",
			Handler:    _Backup_IsReady_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "share/proto/backup.proto",
}
