
### create user
POST http://localhost:8080/api/v1/signup
Content-Type: application/json

{
  "email": "rod8711@gmail.com",
  "password": "12345678"
}
### GET all users
GET http://localhost:8080/api/v1/user


### GET all room
GET http://localhost:8080/api/v1/room/listroom


### get ur ID case you forgot
POST http://localhost:8080/api/v1/getuserbyemail
Content-Type: application/json

{
  "email": "rod8713@gmail.com"
}
###
// rod8711
@userId = 5fd9dfa70f043c4236c09729
// rod8712
@userId2 = 5fd9dfa10f043c4236c09724

### not needed for now
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "email": "rod8711@gmail.com",
  "password": "12345678"
}

### create new room, remember it's id!!
POST http://localhost:8080/api/v1/room/createroom
Content-Type: application/json

{
  "roomName": "foo room",
  "roomType": "group",
  "listUser": [] 
}

###
@roomId = 5fd9dfba26dcb9fb723a8941

### 
POST http://localhost:8080/api/v1/room/addmembertoroom
Content-Type: application/json

{
  "roomId": "{{roomId}}",
  "userIds": ["{{userId}}"]
}

### 
POST http://localhost:8080/api/v1/room/deletemembertoroom
Content-Type: application/json

{
  "roomId": "{{roomId}}",
  "userIds": ["{{userId}}"]
}