

POST http://localhost:8080/api/v1/signup
Content-Type: application/json

{
  "email": "rod8711@gmail.com",
  "password": "top"
}

###
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "Email": "rod8711@gmail.com",
  "Password": "top"
}
