# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import backup_pb2 as backup__pb2


class BackupStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnMessageIn = channel.unary_unary(
                '/proto.Backup/OnMessageIn',
                request_serializer=backup__pb2.Chat.SerializeToString,
                response_deserializer=backup__pb2.Empty.FromString,
                )
        self.IsReady = channel.unary_unary(
                '/proto.Backup/IsReady',
                request_serializer=backup__pb2.Empty.SerializeToString,
                response_deserializer=backup__pb2.Status.FromString,
                )


class BackupServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OnMessageIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BackupServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnMessageIn': grpc.unary_unary_rpc_method_handler(
                    servicer.OnMessageIn,
                    request_deserializer=backup__pb2.Chat.FromString,
                    response_serializer=backup__pb2.Empty.SerializeToString,
            ),
            'IsReady': grpc.unary_unary_rpc_method_handler(
                    servicer.IsReady,
                    request_deserializer=backup__pb2.Empty.FromString,
                    response_serializer=backup__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Backup', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Backup(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnMessageIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Backup/OnMessageIn',
            backup__pb2.Chat.SerializeToString,
            backup__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IsReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Backup/IsReady',
            backup__pb2.Empty.SerializeToString,
            backup__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
