

POST http://localhost:8080/api/v1/user/signup
Content-Type: application/json

{
  "name": "net222",
  "email": "rod82722211@gmail.com",
  "password": "top"
}

###
POST http://localhost:8080/api/v1/user/login
Content-Type: application/json

{
  "Email": "rod82722211@gmail.com",
  "Password": "top"
}

### Test Token
GET http://localhost:8080/api/v1/user/getalltoken



@orgID = 6065876abc4da7c50b4b8494
###
POST http://localhost:8080/api/v1/user/login/{{orgID}}/org
Content-Type: application/json

{
  "Email": "rod82722211@gmail.com",
  "Password": "top"
}

###
POST http://localhost:8080/api/v1/user/logout


###GET USER
GET http://localhost:8080/api/v1/user/user



###Get All message
GET http://localhost:8080/api/v1/message/


### GET ALL Room
GET http://localhost:8080/api/v1/room/listroom



PUT    http://localhost:8080/api/v1/user/updateuserprofile

### GET ALL Room
DELETE http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "userID" : "get user-from id"
}

POST   http://localhost:8080/api/v1/getuserbyemail
Content-Type: application/json

{
  "email" : "get user-from email"
}

GET    http://localhost:8080/api/v1/token
Content-Type: application/json

{
  "userID" : "get user-from id"
}

###GET USER
POST    http://localhost:8080/api/v1/getroombyuserid
Content-Type: application/json

{
  "userID": "5fd83ca80ca261c401b57c76"
}

