@base = http://localhost:8080/api/v1/fcm

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjQ4OWE0ZGFiLWU5Y2MtNGVhZC04N2QwLTllYjU2NDdjNTlkYSIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MjIwOTAxMjk1OCwicm9sZSI6InVzZXIiLCJ1c2VyX2lkIjoiNWZlNDZjMDJjZWQzZTM2MTA5OWNjYzhjIn0.oxlcKJYNzHMuP3NrbOZUPFZKShXka4-ZtA9UqIhd4fk
// see console log when running App
@fcm = ckYOMA85QDC97cW4vqCVUn:APA91bHxF35AuZNCjhMFwcdBlBC0qgPviEXMy1-7QkAeEq6w3lQeQBvH8XB_z8BqTsjGVk2LV3jMbcHfZdPl2PpMAgxc3FX34fxuRvOYqs_FpwHwnvQoAclvMJNlymgw7ldrAWXUwCZd


### GET MY TOKENS
GET {{base}}
Authorization: Bearer {{token}}



### REGSITER
POST {{base}}
Authorization: Bearer {{token}}

{
  "token": "{{fcm}}"
}

### UNREGISTER
DELETE {{base}}
Authorization: Bearer {{token}}

{
  "token": "{{fcm}}"
}


### CHECK STATUS
POST {{base}}/check-status
Authorization: Bearer {{token}}

{
  "token": "{{fcm}}"
}

### CHECK STATUS
POST {{base}}/test-notification
Authorization: Bearer {{token}}

{
  "token": "{{fcm}}"
}
