@base = {{host}}/api/v1/fcm

// see console log when running App
@fcm = ckYOMA85QDC97cW4vqCVUn:APA91bHxF35AuZNCjhMFwcdBlBC0qgPviEXMy1-7QkAeEq6w3lQeQBvH8XB_z8BqTsjGVk2LV3jMbcHfZdPl2PpMAgxc3FX34fxuRvOYqs_FpwHwnvQoAclvMJNlymgw7ldrAWXUwCZd



### GET MY TOKENS
GET {{base}}
Authorization: Bearer {{token}}



### REGSITER
POST {{base}}
Authorization: Bearer {{token}}

{
  "token": "{{fcm}}"
}

### UNREGISTER
DELETE {{base}}
Authorization: Bearer {{token}}

{
  "token": "{{fcm}}"
}


### CHECK STATUS
POST {{base}}/check-status
Authorization: Bearer {{token}}

{
  "token": "{{fcm}}"
}

### CHECK STATUS
POST {{base}}/test-notification
Authorization: Bearer {{token}}

{
  "token": "{{fcm}}"
}


### CHECK STATUS
POST {{base}}/ping
Authorization: Bearer {{token}}

{
  "token": "{{fcm}}"
}
