@base = {{host}}/api/v1/key

# @roomId = 5fef767926dcb936c4e0b6d9
# @roomId = 5ffac45f26dcb94e81f37fe4
@roomId = 6086425b9df1db1d741ce9be

@proxyA = 
@proxyB = 

### get key from master proxy
POST {{base}}/room-key/{{roomId}}
Content-Type: application/json

{
  "publicKey": "asdd=="
}


### tell proxy to generate key
POST {{base}}/room-key/{{roomId}}/generate
Content-Type: application/json

###  GET master proxy
GET {{base}}/master-proxy/{{roomId}}


### get priority
GET {{base}}/priority/{{roomId}}



# "6084fe47c0c954456f4a3430",
#         "6084fe4ec0c954456f4a3433",
#         "6084fe53c0c954456f4a3436"
# 6084fe8dc0c954456f4a3439

###
POST {{base}}/priority/{{roomId}}/{{proxyB}}
Content-Type: application/json

{
  "priority": 3
}



