@base = http://localhost:8080/api/v1/proxy
@proxyId = 5fde119f26dcb940569b15bf
@proxyId2 = 5fde11a326dcb940569b15c0

###
GET {{base}}


###
POST {{base}}
Content-Type: application/json

{
  "name": "Company B"
}


### 
POST {{base}}/{{proxyId}}/reset

