@base = http://localhost:8080/api/v1/proxy
@proxyId = 600025c6584cb6da2059f5bb
@proxyId2 = 


###
GET {{base}}


###
POST {{base}}
Content-Type: application/json

{
  "name": "Local Proxy",
  "ip": "192.168.43.213",
  "port": 8090
}

###
POST {{base}}
Content-Type: application/json

{
  "name": "Local Proxy",
  "ip": "localhost",
  "port": 8090
}


### 
POST {{base}}/{{proxyId}}/reset

