@base = http://localhost:8080/api/v1/room

// org id to create room in
@org = 606a011a26dcb9dde6612d70


@roomA = 607311f626dcb948f4c544f4
@roomB = 

@proxyA = 6066d5c7bc4da719f0c4de2f
@proxyB = 

// me = 5fef73f2315e73be2c81c748
@userA = 6036f05799a05bbc180bd3cb
# @userB = 60001260f0a50a974cee2f95

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjczYTYyMzgwLTlmYWUtNDc2YS04MmU5LWFhNzMzNzM1MzQ1OSIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MjIxODE1MzgwMCwicm9sZSI6InVzZXIiLCJ1c2VyX2lkIjoiNjA2YTAwODUxMTBkYmFiNzc1ZTNjODQyIn0.o55KRNcgqMSJqFOGMwyVPSNrsXW8Fjgo8aL6ZB3YET0

### GET ALL ROOMS
GET {{base}}
Authorization: Bearer {{token}}

### GET My ROOMS
GET {{base}}?me=true
Authorization: Bearer {{token}}

### CREATE ROOM
POST {{base}}/create-group
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "roomName": "LOAD TEST",
  "orgId": "{{org}}"
}

### CREATE ROOM
POST {{base}}/create-private-chat
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "roomName": "Last group",
  "orgId": "{{org}}",
  "userId": "{{userB}}"
}

### GET room by ID
GET {{base}}/id/{{roomA}}

###
DELETE {{base}}/id/{{roomA}}    

### EDIT room
POST {{base}}/id/{{roomA}}/name
Content-Type: application/json

{
  "roomName": "TEST ADD ADMIN"
}

### Get Member
GET {{base}}/id/{{roomA}}/member   

### Get Member as object
GET {{base}}/id/{{roomA}}/member?full=true

### Add Member
POST {{base}}/id/{{roomA}}/member   
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userIds": ["606a0140110dbab775e3c895", "607311a54d193fb8fa6dc3ec", "607311a94d193fb8fa6dc3f1",
  "607311ad4d193fb8fa6dc3f5", "607311b04d193fb8fa6dc3f8"]
}

### remove user
DELETE {{base}}/id/{{roomA}}/member   
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userIds": ["{{userA}}"]
}

### get proxy full
GET {{base}}/{{roomA}}/proxy    
### Add proxy to Room
POST {{base}}/id/{{roomA}}/proxy    
Content-Type: application/json

{
  "proxyIds": ["606b2b3d26dcb9fb60c25cea"]
}



###
DELETE {{base}}/id/{{roomA}}/proxy    
Content-Type: application/json

{
  "proxyIds": ["{{proxyA}}"]
}
###
DELETE {{base}}/id/{{roomA}}


### Get ADmin
GET {{base}}/id/{{roomA}}/admin   
Authorization: Bearer {{token}}

{}

### Add admin
POST {{base}}/id/{{roomA}}/admin   
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userIds": ["{{userB}}"]
}

### remove user
DELETE {{base}}/id/{{roomA}}/admin   
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userIds": ["{{userB}}"]
}
