@base = {{host}}/api/v1/room

// org id to create room in
@org = 608269dc01a5162481476588


@roomA = 60826a1b01a516248147658a
@roomB = 

@proxyA = 
@proxyB = 

// me = 5fef73f2315e73be2c81c748
@userA = 
# @userB = 60001260f0a50a974cee2f95


### GET ALL ROOMS
GET {{base}}
Authorization: Bearer {{token}}

### GET My ROOMS
GET {{base}}?me=true
Authorization: Bearer {{token}}

### CREATE ROOM
POST {{base}}/create-group
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "roomName": "LOAD TEST",
  "orgId": "{{org}}"
}

### CREATE ROOM
POST {{base}}/create-private-chat
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "roomName": "Last group",
  "orgId": "{{org}}",
  "userId": "{{userB}}"
}

### GET room by ID
GET {{base}}/id/{{roomA}}

###
DELETE {{base}}/id/{{roomA}}    

### EDIT room
POST {{base}}/id/{{roomA}}/name
Content-Type: application/json

{
  "roomName": "TEST ADD ADMIN"
}

### Get Member
GET {{base}}/id/{{roomA}}/member   

### Get Member as object
GET {{base}}/id/{{roomA}}/member?full=true

### Add Member
POST {{base}}/id/{{roomA}}/member   
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userIds": ["606a0140110dbab775e3c895", "607311a54d193fb8fa6dc3ec", "607311a94d193fb8fa6dc3f1",
  "607311ad4d193fb8fa6dc3f5", "607311b04d193fb8fa6dc3f8"]
}

### remove user
DELETE {{base}}/id/{{roomA}}/member   
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userIds": ["{{userA}}"]
}

### get proxy full
GET {{base}}/id/{{roomA}}/proxy    
### Add proxy to Room
POST {{base}}/id/{{roomA}}/proxy    
Content-Type: application/json

{
  "proxyIds": ["60826a7201a516248147658d"]
}



###
DELETE {{base}}/id/{{roomA}}/proxy    
Content-Type: application/json

{
  "proxyIds": ["{{proxyA}}"]
}
###
DELETE {{base}}/id/{{roomA}}


### Get ADmin
GET {{base}}/id/{{roomA}}/admin   
Authorization: Bearer {{token}}

{}

### Add admin
POST {{base}}/id/{{roomA}}/admin   
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userIds": ["{{userB}}"]
}

### remove user
DELETE {{base}}/id/{{roomA}}/admin   
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userIds": ["{{userB}}"]
}
