@base = http://localhost:8080/api/v1/room

// org id to create room in
@orgA = 607d46a1bc4da724bb163064


@roomA = 607db45dbc4da70bca9621eb
@roomB = 607db16ebc4da70ad011e58e

@proxyA = 606c36b6bc4da77ecf3097de
@proxyB = 607db0c4bc4da70ad011e58d

// me = 5fef73f2315e73be2c81c748
@userA = 6075e9aa470aacc4ad407d90
# @userB = 60001260f0a50a974cee2f95

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjcxNWIwOGNkLTY3M2MtNDU2Ni04ZGQyLWRmMDAwODlmOGRiMSIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MjIxODgzODM3Nywicm9sZSI6InVzZXIiLCJ1c2VyX2lkIjoiNjA3NWU5YWE0NzBhYWNjNGFkNDA3ZDkwIn0.3htMS-9PUO1ZyJaNc8KwZbGhv54prIYCOP5_vMFSo80

### GET ALL ROOMS
GET {{base}}
Authorization: Bearer {{token}}

### GET My ROOMS
GET {{base}}?me=true
Authorization: Bearer {{token}}

### CREATE ROOM
POST {{base}}/create-group
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "roomName": "Test_view 1",
  "roomType": "GROUP",
  "orgId": "{{orgA}}"
}

### CREATE ROOM
POST {{base}}/create-private-chat
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "roomName": "Last group",
  "orgId": "{{org}}",
  "userId": "{{userB}}"
}

### GET room by ID
GET {{base}}/id/{{roomA}}

###
DELETE {{base}}/id/607d4bb1bc4da724bb163066    

### EDIT room
POST {{base}}/id/{{roomA}}/name
Content-Type: application/json

{
  "roomName": "TEST ADD ADMIN"
}

### Get Member
GET {{base}}/id/{{roomA}}/member   

### Get Member as object
GET {{base}}/id/{{roomA}}/member?full=true

### Add Member
POST {{base}}/id/{{roomA}}/member   
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userIds": ["{{userC}}"]
}

### remove user
DELETE {{base}}/id/{{roomA}}/member   
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userIds": ["{{userA}}"]
}

### get proxy full
GET {{base}}/{{roomA}}/proxy    



### Add proxy to Room
POST {{base}}/id/{{roomA}}/proxy    
Content-Type: application/json

{
  "proxyIds": ["{{proxyA}}"]
}



###
DELETE {{base}}/id/{{roomA}}/proxy    
Content-Type: application/json

{
  "proxyIds": ["{{proxyA}}"]
}
###
DELETE {{base}}/id/{{roomA}}


### Get ADmin
GET {{base}}/id/{{roomA}}/admin   
Authorization: Bearer {{token}}

{}

### Add admin
POST {{base}}/id/{{roomA}}/admin   
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userIds": ["{{userB}}"]
}

### remove user
DELETE {{base}}/id/{{roomA}}/admin   
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userIds": ["{{userB}}"]
}
