@base = http://localhost:8080/api/v1/user


@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImM0ZDE1YzJiLWEzYWMtNGQyYS1hNjE4LTBhNjRmNDZlZThmMSIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MjIwODUzMTg4Miwicm9sZSI6InVzZXIiLCJ1c2VyX2lkIjoiNWZkZTExNDhjM2NhZTY3NDA0MGFlZWJkIn0.xz3WEVwoVQNmOCgWWPlZZ787YK97g1kG_pNtGyWqhzk
### create user
POST {{base}}/signup
Content-Type: application/json

{
  "email": "top-1@gmail.com",
  "password": "topza5353"
}
### GET all users
GET {{base}}/user

### Login
POST {{base}}/login
Content-Type: application/json

{
  "email": "top@gmail.com",
  "password": ""
}

### GET me
GET {{base}}/me
Authorization: Bearer {{token}}

### GET me
POST {{base}}/verify
Content-Type: application/json

{
  "token": "{{token}}"
}