@base = http://localhost:8080/api/v1/user


@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjgyZDRkMDFiLWU3NTItNDQ1ZS04YzJlLTE3N2FjZjhmYjBhMiIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MjIwOTUyODI1MSwicm9sZSI6InVzZXIiLCJ1c2VyX2lkIjoiNWZlZjczZjIzMTVlNzNiZTJjODFjNzQ4In0.pp3eEpS7E7sSq0d-b51iTluz_5hSR8TEM2x7db5Yr0M
### create user
POST {{base}}/signup
Content-Type: application/json

{
  "email": "rod8712@gmail.com",
  "password": "12345678"
}
### GET all users
GET {{base}}/user

### Login
POST {{base}}/login
Content-Type: application/json

{
  "email": "rod8711@gmail.com",
  "password": "12345678"
}

### GET me
GET {{base}}/me
Authorization: Bearer {{token}}

### GET me
POST {{base}}/verify
Content-Type: application/json

{
  "token": "{{token}}"
}

### EDIT me 
PUT {{base}}/me
Authorization: Bearer {{token}}

{
  "name": "User A1 Doge",
  "userType": "iwanttobeadmin",
  "email": "a1@a.com"
}