@base = http://localhost:8080/api/v1/user


@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImNkYzM1NTg1LWY3MzgtNDgyZC1hN2RkLTM1ZWIyNTgxNmJmZiIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MjIwODM5MTMwNCwicm9sZSI6InVzZXIiLCJ1c2VyX2lkIjoiNWZkZTExNDhjM2NhZTY3NDA0MGFlZWJkIn0.zDpL7G7MnPK3gPIfc5D00O6kiL1oAlykycUiIJ00t38
### create user
POST {{base}}/signup
Content-Type: application/json

{
  "email": "rod8711@gmail.com",
  "password": "12345678"
}
### GET all users
GET {{base}}/user

### Login
POST {{base}}/login
Content-Type: application/json

{
  "email": "rod8711@gmail.com",
  "password": "12345678"
}

### Logout
POST {{base}}/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjZhM2UyNmFjLTkzMWYtNDhlYS04YzM0LWMzYWMwODlhODE4OCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MjIwODYwOTQ4Mywicm9sZSI6InVzZXIiLCJ1c2VyX2lkIjoiNWZkZjdlNzAzM2I0MTEzNmQ1YmMwNjQ1In0.bveiYBuXOVTF649UD8CWtLy33mGWFNExhc0JLWq5-5s"
}


### GET me
GET {{base}}/me
Authorization: Bearer {{token}}

### GET me
POST {{base}}/verify
Content-Type: application/json

{
  "token": "{{token}}"
}

### For check refresh token
POST {{base}}/token/refresh
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDkzNDUwMzQsInJlZnJlc2hfdXVpZCI6IjhkNjMzMzYzLTMzZGEtNDdhNC1hNGIyLWRlM2FiYjQwNDMzZiIsInVzZXJfaWQiOiI1ZmRmN2U3MDMzYjQxMTM2ZDViYzA2NDUifQ.UrsCd6Q6qtGSnORhzjQVnbH0hDFzTGxFWUuIA4Xsk-Y"
}