@base = http://localhost:8090


# ### Run code -file
# POST {{base}}/config/runcode
# Content-Type: application/json

# {
#     "Filename":"file",
#     "Lang" : "go"
# }
# ### Kill Process
GET {{base}}/api/v1/config/process/kill?process_name=docker_exec

#js -> node
#python -> python3
#go -> go / file

### GET Proxy-Plugin Enable
GET {{base}}/api/v1/config/plugin/start


### GET Proxy-Plugin disable
GET {{base}}/api/v1/config/plugin/stop


### REGSITER
POST {{base}}/api/v1/config/docker/status
Content-Type: application/json

{
    "server":"docker_upload"
}


