@base = http://localhost:8090


### Run code -file
POST {{base}}/config/runcode
Content-Type: application/json

{
    "Filename":"file",
    "Lang" : "go"
}

### Run Execfile
GET {{base}}/api/v1/config/process/start?file=to_zip_docker_exec


### Kill Process
POST {{base}}/api/v1/config/process/kill?process_name=to_zip_docker_e

#js -> node
#python -> python3
#go -> go / file

### REGSITER
POST {{base}}/api/v1/config/docker/status
Content-Type: application/json

{
    "server":"docker_upload"
}

### New port REGSITER
POST {{base}}/api/v1/config/process/check
Content-Type: application/json

{
    "server":"docker_upload"
}

### New port REGSITER
GET {{base}}/api/v1/config/startimage

### New port REGSITER
POST {{base}}/api/v1/config/containerprocess
Content-Type: application/json

{
    "dockerid":"08392baafeb2"
}

### New port REGSITER
GET {{base}}/api/v1/config/status/set/false


### New port REGSITER
GET {{base}}/api/v1/config/status/set

### New port REGSITER
GET {{base}}/api/v1/config/status/callplugin
