FROM golang
# Set the Current Working Diclerectory inside the container
WORKDIR /app/go_server

# We want to populate the module cache based on the go.{mod,sum} files.
# COPY go.mod .
# COPY go.sum .

# RUN go mod download

COPY . .

# Build the Go app

# Start fresh from a smaller image
# FROM alpine:3.9 
# RUN apk add ca-certificates

# This container exposes port 2020 to the outside world
EXPOSE 2020
EXPOSE 5005

# Run the binary program produced by `go install`
CMD "echo Start Docker-Plugin"
# CMD ["./docker_test/docker_go"]